# Generated by Django 5.1.1 on 2024-09-21 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("country", "0002_alter_game_competition_end_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Athlete_Bio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("athlete_id", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
                ("sex", models.CharField(max_length=10)),
                ("born", models.DateField()),
                ("height", models.FloatField()),
                ("weight", models.FloatField()),
                ("description", models.TextField()),
                ("special_notes", models.TextField()),
                (
                    "country_noc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="country.country",
                    ),
                ),
            ],
        ),
    ]
