# Generated by Django 5.1.1 on 2024-10-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete_bio',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
