# Generated by Django 5.1.3 on 2024-11-18 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete_bio',
            name='country',
        ),
    ]
