# Generated by Django 5.1.3 on 2024-11-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0002_remove_athlete_bio_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete_bio',
            name='country',
            field=models.TextField(default='Unknown'),
        ),
    ]
