# Generated by Django 5.1.3 on 2024-11-18 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0003_athlete_bio_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete_bio',
            name='country',
        ),
    ]
