# Generated by Django 5.1.1 on 2024-10-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0003_alter_athlete_bio_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete_bio',
            name='name',
            field=models.TextField(),
        ),
    ]
