# Generated by Django 5.1.1 on 2024-09-21 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("athlete", "0001_initial"),
        ("country", "0002_alter_game_competition_end_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GamesMedalTally",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("gold", models.IntegerField()),
                ("silver", models.IntegerField()),
                ("bronze", models.IntegerField()),
                ("total", models.IntegerField()),
                (
                    "country_noc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="country.country",
                    ),
                ),
                (
                    "edition_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="country.game"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                ("result_id", models.IntegerField(primary_key=True, serialize=False)),
                ("event_title", models.CharField(max_length=255)),
                ("sport", models.CharField(max_length=255)),
                ("sport_url", models.CharField(max_length=255)),
                ("result_location", models.CharField(max_length=255)),
                ("result_participants", models.IntegerField()),
                ("result_countries", models.IntegerField()),
                ("result_format", models.TextField()),
                ("result_detail", models.TextField()),
                ("result_description", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "edition_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="country.game"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sport", models.CharField(max_length=255)),
                ("event", models.CharField(max_length=255)),
                ("pos", models.CharField(max_length=255)),
                ("medal", models.CharField(max_length=255)),
                ("isTeamSport", models.BooleanField()),
                (
                    "athlete_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="athlete.athlete_bio",
                    ),
                ),
                (
                    "country_noc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="country.country",
                    ),
                ),
                (
                    "edition_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="country.game"
                    ),
                ),
                (
                    "result_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="competition.result",
                    ),
                ),
            ],
        ),
    ]
