# Generated by Django 5.1.1 on 2024-09-25 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0003_alter_game_edition_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedalTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.IntegerField()),
                ('silver', models.IntegerField()),
                ('bronze', models.IntegerField()),
                ('country_noc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='country.country')),
                ('edition_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='country.game')),
            ],
        ),
    ]
