# Generated by Django 5.1.1 on 2024-10-26 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athlete', '0001_initial'),
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedalTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.IntegerField()),
                ('silver', models.IntegerField()),
                ('bronze', models.IntegerField()),
                ('country_noc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='country.country')),
                ('edition_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='country.game')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('result_id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_title', models.CharField(max_length=255)),
                ('sport', models.CharField(max_length=255)),
                ('sport_url', models.CharField(max_length=255)),
                ('result_location', models.CharField(max_length=255)),
                ('result_participants', models.IntegerField()),
                ('result_countries', models.IntegerField()),
                ('result_format', models.TextField()),
                ('result_detail', models.TextField()),
                ('result_description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('edition_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='country.game')),
            ],
        ),
        migrations.CreateModel(
            name='MedalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medal', models.CharField(max_length=255)),
                ('athlete_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='athlete.athlete_bio')),
                ('country_noc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='country.country')),
                ('edition_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='country.game')),
                ('result_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='competition.result')),
            ],
        ),
        migrations.CreateModel(
            name='EventResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=255)),
                ('event', models.CharField(max_length=255)),
                ('pos', models.CharField(max_length=255)),
                ('isTeamSport', models.BooleanField()),
                ('athlete_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='athlete.athlete_bio')),
                ('country_noc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='country.country')),
                ('edition_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='country.game')),
                ('result_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='competition.result')),
            ],
        ),
    ]
