# Generated by Django 5.1.1 on 2024-10-18 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0003_alter_athlete_bio_name'),
        ('competition', '0002_medalresult_remove_result_edition_id_and_more'),
        ('country', '0003_alter_game_edition_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventresult',
            name='athlete_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='athlete.athlete_bio'),
        ),
        migrations.AlterField(
            model_name='eventresult',
            name='country_noc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='country.country'),
        ),
        migrations.AlterField(
            model_name='eventresult',
            name='edition_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='country.game'),
        ),
        migrations.AlterField(
            model_name='medalresult',
            name='athlete_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='athlete.athlete_bio'),
        ),
        migrations.AlterField(
            model_name='medalresult',
            name='country_noc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='country.country'),
        ),
        migrations.AlterField(
            model_name='medalresult',
            name='edition_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='country.game'),
        ),
        migrations.CreateModel(
            name='GamesMedalTally',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('gold', models.IntegerField()),
                ('silver', models.IntegerField()),
                ('bronze', models.IntegerField()),
                ('total', models.IntegerField()),
                ('country_noc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='country.country')),
                ('edition_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='country.game')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('result_id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_title', models.CharField(max_length=255)),
                ('sport', models.CharField(max_length=255)),
                ('sport_url', models.CharField(max_length=255)),
                ('result_location', models.CharField(max_length=255)),
                ('result_participants', models.IntegerField()),
                ('result_countries', models.IntegerField()),
                ('result_format', models.TextField()),
                ('result_detail', models.TextField()),
                ('result_description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('edition_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='country.game')),
            ],
        ),
        migrations.AlterField(
            model_name='eventresult',
            name='result_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='competition.result'),
        ),
        migrations.AlterField(
            model_name='medalresult',
            name='result_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='competition.result'),
        ),
    ]
