# Generated by Django 5.1.3 on 2024-11-18 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_alter_result_end_date_alter_result_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventresult',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventresult',
            name='sport',
        ),
    ]
