# Generated by Django 5.1.1 on 2024-10-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_alter_eventresult_athlete_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventresult',
            name='athlete_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='eventresult',
            name='country_noc',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='eventresult',
            name='edition_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='eventresult',
            name='result_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medalresult',
            name='athlete_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medalresult',
            name='country_noc',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medalresult',
            name='edition_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='medalresult',
            name='result_id',
            field=models.IntegerField(),
        ),
    ]
