# Generated by Django 5.1.1 on 2024-10-19 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0005_alter_athlete_bio_name'),
        ('competition', '0004_alter_eventresult_athlete_id_and_more'),
        ('country', '0003_alter_game_edition_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventresult',
            name='athlete_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='athlete.athlete_bio'),
        ),
        migrations.AlterField(
            model_name='eventresult',
            name='country_noc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='country.country'),
        ),
        migrations.AlterField(
            model_name='eventresult',
            name='edition_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='country.game'),
        ),
        migrations.AlterField(
            model_name='eventresult',
            name='result_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='competition.result'),
        ),
        migrations.AlterField(
            model_name='medalresult',
            name='athlete_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='athlete.athlete_bio'),
        ),
        migrations.AlterField(
            model_name='medalresult',
            name='country_noc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='country.country'),
        ),
        migrations.AlterField(
            model_name='medalresult',
            name='edition_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='country.game'),
        ),
        migrations.AlterField(
            model_name='medalresult',
            name='result_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='competition.result'),
        ),
    ]
