# Generated by Django 5.1.3 on 2024-11-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_remove_eventresult_event_remove_eventresult_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventresult',
            name='country_noc',
        ),
        migrations.RemoveField(
            model_name='medalresult',
            name='country_noc',
        ),
    ]
