# Generated by Django 5.1.3 on 2024-11-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_remove_eventresult_country_noc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventresult',
            name='isTeamSport',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='eventresult',
            name='pos',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medalresult',
            name='medal',
            field=models.CharField(max_length=10),
        ),
    ]
