# Generated by Django 5.1.3 on 2024-11-19 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_alter_eventresult_isteamsport_alter_eventresult_pos_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='eventresult',
        #     name='edition_id',
        # ),
        # migrations.RemoveField(
        #     model_name='medalresult',
        #     name='edition_id',
        # ),
    ]
