# Generated by Django 5.1.3 on 2024-11-19 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0007_remove_eventresult_edition_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventresult',
            name='edition_id',
        ),
        migrations.RemoveField(
            model_name='medalresult',
            name='edition_id',
        ),
    ]
