# Generated by Django 5.1.1 on 2024-10-26 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('noc', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('edition', models.CharField(max_length=255)),
                ('edition_id', models.AutoField(primary_key=True, serialize=False)),
                ('edition_url', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('country_flag_url', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_held', models.BooleanField()),
                ('competition_start_date', models.DateField(blank=True, null=True)),
                ('competition_end_date', models.DateField(blank=True, null=True)),
                ('country_noc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='country.country')),
            ],
        ),
    ]
