# Generated by Django 5.1.1 on 2024-09-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("country", "0002_alter_game_competition_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="edition_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
